[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Experience"
  pageRef = "experience"
  weight = 20

[[main]]
  name = "Services"
  pageRef = "services"
  weight = 25

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 30
